export const APP_CONSTANTS = {
  UNAUTHENTICATED: "Unauthenticated",
  BASIC_TIER: "basic",
  PRO_TIER: "pro",
  ENGLISH: "English",
  SUCCESS: "success",
  SAVE: "Save",
  CLOSE: "Close",
  SOURCE_NOTE: "note",
  SOURCE_NOTEBOOK: "notebook",
  NAME_EMPTY: "Enter your name.",
  EMAIL_INVALID: "Enter a valid email address.",
  PASSWORD_LENGTH_SHORT: "Password must be at least 8 characters.",
  PASSWORD_MISMATCH: "Passwords do not match.",
  EMAIL_TAKEN: "This email is already taken.",
  TOO_MANY_ATTEMPTS: "Too many attempts. Try again later.",
  BAD_NETWORK: "Network error. Check your internet connection and try again.",
  USER_DISABLED: "This email has been disabled.",
  INVALID_CREDENTIALS: "Wrong email or password.",
  ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL:
    "An account already exists with this email using a different sign-in method.",
  POPUP_BLOCKED:
    "Your browser blocked the sign-in popup. Please allow popups and try again.",
  POPUP_CLOSED_BY_USER:
    "Sign-in popup was closed before completing the sign-in.",
  UNAUTHORIZED_DOMAIN:
    "This app is not authorized for Google sign-in. Contact support.",
  WITH_EMAIL: "email",
  WITH_GOOGLE: "google",
  NULL: "null",
  UNKNOWN_ERROR: "An unknown error occurred. Try again later.",
  DASHBOARD_PAGE: "dashboard",
  NOTES_PAGE: "notes",
  NO_NOTES:
    "No notes in sight. Maybe they’re on vacation? \n Let’s bring new ones to life!",
  NO_TAGGED_ITEMS:
    "Hmmm... it looks like you haven’t tagged anything yet.\nBut hey, it's never too late to stay organized.",
  NO_UNTAGGED_ITEMS: "Good news! You don't have any unntagged items.",
  NO_PINNED_ITEMS:
    "Nothing pinned yet. Got a favorite? Hit \n the pin icon to keep it close.",
  NO_RECENT_ITEMS:
    "Nothing recent to show — but don’t worry, \n we’ll keep this space updated as you go.",
  NOTEBOOKS_PAGE: "notebooks",
  SETTINGS_PAGE: "settings",
  TAGGED_ITEMS: "taggedItems",
  UNTAGGED_ITEMS: "untaggedItems",
  PINNED_ITEMS: "pinnedItems",
  RECENT_ITEMS: "recentItems",
  VIEW_GRID: "gridView",
  VIEW_TABLE: "tableView",
  NOTE_EDITOR_PLACEHOLDER: "Write something...",
  VIEW_NOTE_EDITOR: "noteEditorView",
  DELETE_NOTE_MODAL_TITLE: "Delete this note?",
  DELETE_NOTE_MODAL_TEXT_CONTENT:
    "This note wil be permanently deleted. This action cannot be undone. Are you sure you want to continue?",
  DELETE_NOTEBOOK_MODAL_TITLE: "Delete this notebook?",
  DELETE_NOTEBOOK_MODAL_TEXT_CONTENT:
    "This notebook wil be permanently deleted along with all the notes it may contain. This action cannot be undone. Are you sure you want to continue?",
  DELETE_NOTES_MODAL_TITLE: "Delete all notes?",
  DELETE_NOTES_MODAL_TEXT_CONTENT:
    "This will permanently delete all your notes. This action cannot be undone. Are you sure you want to continue?",
  DELETE_NOTEBOOKS_MODAL_TITLE: "Delete all notebooks?",
  DELETE_NOTEBOOKS_MODAL_TEXT_CONTENT:
    "This will permanently delete all your notebooks and their contents. This action cannot be undone. Are you sure you want to continue?",
  DELETE_ACCOUNT_MODAL_TITLE: "Delete your account?",
  DELETE_ACCOUNT_MODAL_TEXT_CONTENT:
    "This will permanently delete your account and all associated data. This action cannot be undone. Are you sure you want to continue?",
  SUCCESS_MODAL_TITLE: "Success",
  SUCCESS_MODAL_TEXT_CONTENT: "Your action was completed successfully.",
  ERROR_MODAL_TITLE: "Something went wrong",
  ERROR_MODAL_TEXT_CONTENT:
    "We couldn't complete your request. Please try again.",
  SIGN_OUT_MODAL_TITLE: "Sign out?",
  SIGN_OUT_MODAL_TEXT_CONTENT:
    "You will be signed out of your account. You can sign back in at any time. Are you sure you want to continue?",
  EMAIL_VERIFICATION_MODAL_SUCCESS: "Check your inbox",
  EMAIL_VERIFICATION_MODAL_SUCCESS_TEXT_CONTENT:
    "We've sent a verification link to your email. Please check your inbox to complete the verification. Refresh the page once you're done.",
  VERIFY_EMAIL: "Verify email from settings",
  FIELD_EMPTY: "One or more fields are empty. Please fill them and try again.",
  UNSAVED_CHANGES: "Unsaved changes",
  UNSAVED_CHANGES_TEXT_CONTENT:
    "You have unsaved changes. Closing the note will permanently discard them.",
  GENERIC_MODAL: "genericModal",
  CREATE_NOTE_MODAL: "createNoteModal",
  CREATE_NOTEBOOK_MODAL: "createNotebookModal",
  EDIT_NOTE_MODAL: "editNoteModal",
  EDIT_NOTEBOOK_MODAL: "editNotebookModal",
  EDITOR_LINK_MODAL: "editorLinkModal",
  EDITOR_YOUTUBE_LINK_MODAL: "editorYouTubeLinkModal",
  MATH_EQUATION_MODAL: "mathEquationModal",
  SPEECH_RECOGNITION_MODAL: "speechRecognitionModal",
  NO_NOTEBOOKS:
    "We checked twice. Still no notebooks.\n Maybe it's time to create one?",
  NO_TAGS: "No tags here yet. Add some to keep things easy to find.",
  NOTE_EMPTY:
    "Don't be shy, give your note some love! Start typing your masterpiece.",
  TAG_LIMIT: 15,
  ULTRA_LARGE: "ultra-large",
  LARGE: "large",
  MEDIUM: "medium",
  COMPACT: "compact",
  RECENT_LIMIT: 20,
  CREATE: "Create",
  INSERT: "Insert",
  SIGN_OUT: "Sign out",
  EDIT: "Save changes",
  SEND: "Send",
  DELETE: "Delete",
  CANCEL: "Cancel",
  OK: "Okay",
  HOUR: 3600000,
};
